### ISSUE TITLE
Tidy up the repository

### ISSUE THREAD

**Issue by alastairs** [GiveCampUK/GiveCRM#18]
There is some sensitive information in the repository (a list of everyone's name, Twitter handles and email addresses).

It is not considered best practice to check in NuGet packages to the repository.  

The repository should be cleaned up a bit to remove these extra items.

**Comment by AnthonySteele** [comment]
I agree that some files have to go.
For nuget packages in the repo, I've seen different opinions, and haven't seen a definitive argument either way. Practice varies: http://twtpoll.com/un65my

So long as everyone is on the same page we should be OK, which is why this sort of thing should be written down somewhere.

**Comment by stack72** [comment]
If we are going to take the nuget packages out then I need to know as I am writing a build script for it and will need to include that

**Comment by alastairs** [comment]
I've added a wiki to both repositories that can be used to document things like NuGet packages, coding standards, packages in use, etc.  I've got to get off to work shortly though, so all I've done is push the button for now.

**Comment by AnthonySteele** [comment]
Excellent!
